name: Test the source code in the repository
on:
  push:
    branches: [main]
jobs:
  code-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm i
      - name: Run Jest
        run: npm run test
